utils::globalVariables(c(
  ".data", "Date Time",
  "SC", "X1", "X2",
  "a_t", "auto_disabled", "b_t", "c_t",
  "calibration_data", "cell_constant",
  "chla_post_cal", "chla_post_clean", "chla_pre_clean",
  "closest", "cols",
  "cond_post_cal", "cond_post_clean", "cond_pre_clean",
  "contains", "correct_calibration", "created",
  "data_count", "date_time", "device_model", "device_sn",
  "discard", "drift_1", "drift_2",
  "eligible_for_processing",
  "f01", "f99", "f_slope_behind_01", "f_slope_behind_99",
  "failure_count",
  "fdom_post_cal", "fdom_post_clean", "fdom_pre_clean",
  "file_date", "group_by",
  "html_elements", "html_table", "html_text",
  "hv_sites", "if_else", "instrument", "intrasensor_flags",
  "is_scalar_character", "isi_hv_timestamp",
  "join_by", "keep",
  "last_calibrated", "last_success", "local_dt_str",
  "mWater_data", "make_clean_names", "minutes",
  "network",
  "offset", "offset_delta", "offset_final", "offset_lag", "offset_lead", "offset_units",
  "orp_post_cal", "orp_post_clean", "orp_pre_clean", "orp_solution",
  "p_h",
  "ph_post_cal", "ph_post_clean", "ph_pre_clean",
  "pluck_exists", "point",
  "post_cal_chla", "post_cal_fdom", "post_clea_fdom", "post_clean_chla", "post_measurement",
  "pre_clean_chla", "pre_clean_fdom", "pre_measurement",
  "rdo_post_cal", "rdo_post_clean", "rdo_pre_clean",
  "regex", "replace_na", "rowwise",
  "season", "sensor", "sensor_date", "sensor_date_lag", "sensor_date_lead",
  "sensor_serial", "sensor_sn", "separate_wider_delim", "serial_number", "set_names",
  "site_order_list", "site_parameter", "slice_min",
  "slope", "slope_delta", "slope_final", "slope_lag", "slope_lead", "slope_units",
  "smoothed_mean", "sonde_date", "sonde_serial",
  "str_detect", "str_split", "str_split_1", "success",
  "time_offset", "try_again",
  "turb_post_cal", "turb_post_clean", "turb_pre_clean",
  "ungroup", "unit", "unnest",
  "vals", "visit_group", "tightest_r", "failed",
  "r2_s_right", "r2_s_center", "r2_l_right", "r2_l_center",
  "DO_drift_binary", "right", "center", "raw",
  "wt", "zero_offset"
))
